AllCops:
  Include:
    - '**/Gemfile'
    - lib/**/*
    - spec/**/*
    - knife_skeleton.gemspec
  Exclude:
    - files/**/*
    - templates/**/*
MethodLength:
  Exclude:
    - lib/**/*
ClassLength:
  Exclude:
    - lib/**/*
ParameterLists:
  Exclude:
    - lib/**/*
