# -*- coding: utf-8 -*-
source 'https://rubygems.org'

gem 'chef', '~> 12.0.3'
gem 'berkshelf'
gem 'rake'

group :lint do
  gem 'rubocop'
  gem 'foodcritic'
end

group :unit do
  gem 'chefspec'
end

group :kitchen do
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
  gem 'kitchen-openstack'
end
